EcommerceDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='homepage'),
    path('product/<slug:slug>/', views.ProductView.as_view(), name='product'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
    path('category/', views.categories, name='categories'),
    path('category/<slug:slug>/', views.category , name='category'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('build/', views.build, name='buildpc'),
    path('load_cpu/', views.load_cpu, name='ajax_load_cpu'),
    path('load_ram/', views.load_ram, name='ajax_load_ram'),
    # Page
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('returnpolicy/', views.returnpolicy, name='returnpolicy'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.db.models.signals import post_save


# Category
class Category(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def get_category_url(self):
        return reverse('core:category', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


# All product type model
# Brand
class Brand(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Socket(main, CPU)
class Socket(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Series CPU
class SeriesCPU(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Wattage Power\
class Wattage(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Ram type
class MemoryType(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Ram, video card capacity
class Capacity(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Resolution monitor
class Resolution(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Screen size monitor
class ScreenSize(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title


# Product
class Product(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    price = models.FloatField(max_length=5, null=False, blank=False)
    discount_price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, on_delete=models.SET_NULL, null=True)
    brandname = models.ForeignKey(Brand, blank=True, on_delete=models.SET_NULL, null=True)
    screensize = models.ForeignKey(ScreenSize, blank=True, on_delete=models.SET_NULL, null=True)
    resolution = models.ForeignKey(Resolution, blank=True, on_delete=models.SET_NULL, null=True)
    socket = models.ForeignKey(Socket, blank=True, on_delete=models.SET_NULL, null=True)
    wattage = models.ForeignKey(Wattage, blank=True, on_delete=models.SET_NULL, null=True)
    seriescpu = models.ForeignKey(SeriesCPU, blank=True, on_delete=models.SET_NULL, null=True)
    memory_type = models.ForeignKey(MemoryType, blank=True, on_delete=models.SET_NULL, null=True)
    capacity = models.ForeignKey(Capacity, blank=True, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(null=True, blank=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def get_absolute_url(self):
        return reverse('core:product', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


# All product type model - END

# Customer model
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, blank=True)

    def create_customer(sender, **kwargs):
        if kwargs['created']:
            user_profile = Customer(user=kwargs['instance'], name=kwargs['instance'])
            user_profile.save()

    post_save.connect(create_customer, sender=User)

    def __str__(self):
        return self.name


# All order models
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_order = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True, unique=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Order ' + str(self.order)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class Shipping(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    phone = models.CharField(max_length=12, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    address = models.CharField(max_length=300, blank=False)
    city = models.CharField(max_length=30, blank=False)
    state = models.CharField(max_length=30, blank=False)
    zipcode = models.CharField(max_length=10, blank=False)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

# End order models

core/views.py
import json
import datetime
from .models import *
from .filters import *
from django.http import JsonResponse
from .utils import cookieCart, cartData, guestOrder
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Home page
class HomeView(ListView):
    def get(self, request):
        template_name = 'home.html'
        products = Product.objects.all().order_by('-id')
        paginator = Paginator(products, 8)
        page = request.GET.get('page', 1)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        cartItems = cart_items(request)
        context = {
            'products': products,
            'cartItems': cartItems,
            'page': page,
        }
        return render(request, template_name, context)


# Product detail page
class ProductView(DetailView):
    def get(self, request, slug):
        template_name = 'product.html'
        product = get_object_or_404(Product, slug=slug)
        cartItems = cart_items(request)
        context = {'product': product, 'cartItems': cartItems}
        return render(request, template_name, context)


# Display product all categories
def categories(request):
    products = Product.objects.all().order_by('-id')
    categorys = Category.objects.all().order_by('-id')
    cartItems = cart_items(request)

    # Filter
    myFilter = ProductFilter(request.GET, queryset=products)
    products = myFilter.qs

    # Paginator
    paginator = Paginator(products, 9)
    page = request.GET.get('page', 1)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    template_name = 'category.html'
    context = {
        'products': products,
        'cartItems': cartItems,
        'categorys': categorys,
        'page': page,
        'myFilter': myFilter
    }
    return render(request, template_name, context)


# Display product in a category
def category(request, slug):
    category_title = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category_title).order_by('-id')
    cartItems = cart_items(request)
    # Filter
    myFilter = ProductFilter(request.GET, queryset=products)
    products = myFilter.qs

    context = {
        'products': products,
        'cartItems': cartItems,
        'category_title': category_title,
        'myFilter': myFilter
    }
    template_name = 'category_details.html'
    return render(request, template_name, context)


# Cart page
def cart(request):
    data = cartData(request)
    items = data['items']
    order = data['order']
    quantity = data['quantity']
    cartItems = cart_items(request)
    context = {'items': items, 'order': order, 'quantity': quantity, 'cartItems': cartItems}
    return render(request, 'cart.html', context)


# Get cart items function
def cart_items(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        cartItems = order.get_cart_items
    else:
        try:
            cart = json.loads(request.COOKIES['cart'])
        except:
            cart = {}
        cartItems = 0
        for i in cart:
            cartItems += cart[i]["quantity"]
    return cartItems


# Checkout page
def checkout(request):
    data = cartData(request)
    items = data['items']
    order = data['order']
    quantity = data['quantity']
    context = {'items': items, 'order': order, 'quantity': quantity}
    return render(request, 'checkout.html', context)


# Update quantity
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


# Process Order
def processOrder(request):
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = datetime.datetime.now().timestamp()

    if total == order.get_cart_total:
        order.complete = True
    order.save()
    Shipping.objects.create(
        customer=customer,
        order=order,
        address=data['shipping']['address'],
        city=data['shipping']['city'],
        state=data['shipping']['state'],
        zipcode=data['shipping']['zipcode'],
    )
    return JsonResponse('Payment submitted..', safe=False)


# Build PC
def build(request):
    mainboards = Product.objects.filter(category__title__contains="Motherboards")
    power = Product.objects.filter(category__title__contains="Power Supplies")
    monitors = Product.objects.filter(category__title__contains="Monitors")
    storage = Product.objects.filter(category__title__contains="Data Storage")
    videocard = Product.objects.filter(category__title__contains="Video Cards")
    cartItems = cart_items(request)
    context = {
        'cartItems': cartItems,
        'motherboards': mainboards,
        'power': power,
        'monitors': monitors,
        'storage': storage,
        'videocard': videocard,
    }
    return render(request, 'build.html', context)


# Load Processors (Build PC)
def load_cpu(request):
    socket_type = request.GET.get('socket')
    processors = Product.objects.filter(category__title="Processors", socket__title=socket_type)
    return render(request, 'processors.html', {'processors': processors})


# Load Memory (Build PC)
def load_ram(request):
    ram_type = request.GET.get('ramtype')
    memory = Product.objects.filter(category__title__contains="Memory", memory_type__title=ram_type)
    print(ram_type)
    return render(request, 'memory.html', {'memory': memory})


# About
def about(request):
    return render(request, 'about.html')


# Contact
def contact(request):
    return render(request, 'contact.html')


# Return Policy
def returnpolicy(request):
    return render(request, 'returnpolicy.html')

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block title %} {% endblock title %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        {% block head %} {% endblock head %}
        <script async src="https://kit.fontawesome.com/ff64d37b6d.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {% include 'get_data.html' %}
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'core:homepage' %}"><img style="height:70px !important; width: auto !important;" src="https://90a1c75758623581b3f8-5c119c3de181c9857fcb2784776b17ef.ssl.cf2.rackcdn.com/images_sf_MC_logo.png" alt="Logo"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:homepage' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:categories' %}">Shop</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"  href="{% url 'core:buildpc' %}">Build PC</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:about' %}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
                            </li>
                        </ul>
                        <div>
                            <a class="btn btn-info btn-sm" href="{% url 'core:cart' %}">
                                <i class="fa fa-shopping-cart"></i> Cart
                                <span class="badge badge-light">{% block cart_items %}{% endblock cart_items %}</span>
                            </a>
                            {% if request.user.is_authenticated %}
                                <a class="btn btn-secondary btn-sm" href="{% url 'account_logout' %}">
                                    Logout
                                </a>
                            {% else %}
                                <a class="btn btn-success btn-sm" href="{% url 'account_login' %}">
                                    Login
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main">
            {% block content %}
            {% endblock content %}
        </main>
        <footer style="background-color: #e9ecef;">
            <div class="container py-4">
                <div class="row">
                    <div class="col-6 col-md">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="d-block mb-2">
                            <circle cx="12" cy="12" r="10"></circle>
                            <line x1="14.31" y1="8" x2="20.05" y2="17.94"></line>
                            <line x1="9.69" y1="8" x2="21.17" y2="8"></line>
                            <line x1="7.38" y1="12" x2="13.12" y2="2.06"></line>
                            <line x1="9.69" y1="16" x2="3.95" y2="6.06"></line>
                            <line x1="14.31" y1="16" x2="2.83" y2="16"></line>
                            <line x1="16.62" y1="12" x2="10.88" y2="21.94"></line>
                        </svg>
                        <small class="d-block mb-3 text-muted">&copy; 2020-2021</small>
                    </div>
                    <div class="col-6 col-md">
                    <h5>Quick Links</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'core:categories' %}">Shop by category</a></li>
                            <li><a class="text-muted" href="{% url 'core:buildpc' %}">Build PC</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Customer Service</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'core:contact' %}">Contact</a></li>
                            <li><a class="text-muted" href="{% url 'core:returnpolicy' %}">Return Policy</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Our Company</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'core:about' %}">About</a></li>
                            <li><a class="text-muted" href="{% url 'account_login' %}">Member</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                Copyright © 2021 | All Right Reserved
                <br>
                Made with <i class="fas fa-heart"></i> by
                <a class="text-white" href="https://www.hoangnam.cc/">Hoangnam.cc</a>
            </div>
            <!-- Copyright -->
        </footer>
        <!-- Script -->
        {% block script %}  {% endblock script %}
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    </body>
</html>

core/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Your cart - Micro Center</title>
{% endblock title %}
{% block content %}
    <div class="container shopping-cart">
        <div class="block-heading">
            <h2>Shopping Cart</h2>
        </div>
        <div class="content">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="items">
                        {% for item in items %}
                        <div class="product">
                            <div class="row">
                                <div class="col-md-3">
                                    <img class="img-fluid mx-auto d-block image" src="{{ item.product.imageURL }}">
                                </div>
                                <div class="col-md-8">
                                    <div class="info">
                                        <div class="row">
                                            <div class="col-md-5 product-name">
                                                <div class="product-name">
                                                    <a href="{{ item.product.get_absolute_url }}">{{ item.product.title }}</a>
                                                </div>
                                            </div>
                                            <div class="col-md-4 quantity">
                                                <label>Quantity</label>
                                                <div class="input-group">
                                                    <a href="" class="update-cart" data-product="{{ item.product.id }}" data-action="remove"><input
                                                           type="button" value="-"
                                                           class="button-minus"></a>
                                                    <input type="number" value="{{ item.quantity }}" name="quantity"
                                                           class="quantity-field" disabled>
                                                    <input data-product="{{ item.product.id }}" data-action="add"
                                                           type="button" value="+"
                                                           class="button-plus update-cart"></a>
                                                </div>
                                            </div>
                                            <div class="col-md-3 price">
                                                <span>${{ item.product.price|floatformat:2 }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <div class="summary">
                        <h3>Summary</h3>
                        <div class="summary-item"><span class="text">Subtotal
                                {% if cartItems > 1 %}
                                    ({{ cartItems }} items)
                                {% else %}
                                    ({{ cartItems }} item)
                                {% endif %}
                                </span><span class="price">${{ order.get_cart_total|floatformat:2 }}</span>
                        </div>
                        <div class="summary-item"><span class="text">Total</span><span class="price">${{ order.get_cart_total|floatformat:2 }}</span>
                        </div>
                        <div>
                            <a href="{% url 'core:checkout' %}" type="button" class="btn btn-primary btn-lg btn-block">Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/product.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock script %}

core/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>About - Micro Center</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="p-5">
        <h1>About Micro Center</h1>
        <h4>Here for Your Essential Communication and Information Technology Needs</h4>
    </div>
</div>
{% endblock content %}

core/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Micro Center - Computer & Electronic</title>
{% endblock title %}

{% block cart_items %}
    {{ cartItems }}
{% endblock cart_items %}

{% block content %}
    <div id="demo" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
        </ul>
        <!-- The slideshow -->
        <div class="carousel-inner">
            <div class="carousel-item active" style="height: 480px;">
                <img src="/images/banner1.jpg" alt="" style="width: inherit;">
            </div>
            <div class="carousel-item" style="height: 480px;">
                <img src="/images/banner2.jpg" alt="" style="width: inherit;">
            </div>
        </div>
        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
    <div class="container px-5 py-5 mx-auto">
        <h3 class="h3" align="center">Our Products</h3>
        <div class="row">
            {% for product in products %}
            <div class="col-md-3 col-sm-6">
                <div class="product-grid4">
                    <div class="product-image4">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="pic-1" src="{{ product.imageURL }}"></a>
                    </div>
                    <div class="product-content">
                        <p class="title"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></p>
                        <div class="price">
                            {% if product.discount_price %}
                            <span>${{ product.price|floatformat:2 }}</span> ${{ product.discount_price|floatformat:2 }}
                            {% else %}
                            ${{ product.price|floatformat:2 }}
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-12">
            <nav>
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">Previous</a>
                        </li>
                    {% endif %}

                    {% for i in products.paginator.page_range %}
                        {% if products.number == i %}
                            <li class="page-item active">
                                <a class="page-link">{{ i }}<span class="sr-only">(current)</span></a>
                            </li>
                        {% elif i > products.number|add:'-2' and i < products.number|add:'2' %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if products.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <a href="{% url 'core:buildpc' %}"><img src="/images/builpc.jpg" alt="Build PC"
                                                style="margin-left: auto; margin-right: auto; width: inherit; display: block;"></a>
    </div>
{% endblock content %}

core/templates/processors.html
{% for cpu in processors %}
<a class="dropdown-item" id="{{cpu.id}}" title="{{ cpu.title }}" data-price="{{cpu.price}}" data-idbefore="processors"
   onClick="someFunc(this.id, this.title, this.price);"><img style="width: 50px !important; height: auto;" src="{{ cpu.imageURL }}">{{cpu.title}}</a>
{% endfor %}

core/templates/returnpolicy.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    <title>Policy - Micro Center</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="p-5">
        <h1>Return or exchange timeframes</h1>
        <h4>Eligible return or exchange timeframes are from the date of purchase:</h4>
        <p>15 calendar days</p>
        <ul>
            <li>Camcorders and projectors</li>
            <li>Desktop / Notebook computers</li>
            <li>Digital cameras</li>
            <li>Motherboards</li>
            <li>Processors</li>
            <li>Tablets</li>
            <li>3D printers, 3D scanners, and CD/DVD duplicators</li>
        </ul>
        <h1>Refunds</h1>
        <p>Micro Center is not responsible for expenses, fees or additional costs incurred as a result of defective or
            incompatible products</p>
    </div>
</div>
{% endblock content %}